[build]
  command = "gatsby build"
  publish = "/opt/build/repo/public/"

[context.production]
  command = "echo 'production'"
  environment = {CONTENTFUL_SPACE_ID = "8ioz9f3k4doo", CONTENTFUL_ACCESS_TOKEN = "WVVEDWML5_j2LMMHHgnf6Wt-e96XWxSyYRvfsLK9YeA"}
